# Limpeza e Análise de Dados de Vendas

In [1]:
import pandas as pd

In [2]:
vendas = pd.read_csv('data_raw.csv')

In [3]:
vendas.head()

   ID        Data                    Produto    Categoria  Quantidade    Preço
0   1  2023-11-24           Teclado Mecânico  Periféricos         1.0   333.93
1   2  2023-02-22                  Cabo HDMI   Acessórios         5.0    16.11
2   3  2023-02-17  Smartphone Samsung Galaxy    Celulares         1.0  2210.24
3   4  2023-11-29           Caixa de Som JBL        Áudio         2.0   553.56
4   5  2023-01-04             Webcam Full HD  Periféricos         2.0   235.06

In [5]:
vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          309 non-null    int64
 1   Data        309 non-null    object
 2   Produto     309 non-null    object
 3   Categoria   304 non-null    object
 4   Quantidade  304 non-null    float64
 5   Preço       304 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 14.6+ KB

A verificação inicial de dados faltantes df.info() revelou a presença de missing values (dados faltantes) em algumas colunas:
`Quantidade`, `Categoria` e `Preço` (5 em cada)
As variáveis `ID`, `Data`, `Produto` estão completas. Os tipos de dados estao adequados, com as variáveis numéricas sendo do tipo float, o ID sendo int e as categóricas do tipo object.

In [6]:
vendas.describe()

               ID  Quantidade        Preço
count  309.000000  304.000000   304.000000
mean   155.000000    2.536184   822.897905
std     89.344838    1.334490  1238.630515
min      1.000000    1.000000    15.330000
25%     78.000000    2.000000    71.050000
50%    155.000000    2.000000   314.715000
75%    232.000000    3.000000   794.372500
max    309.000000   10.000000  6662.629970

* Dados Faltantes:
 * A contagem count confirma a presença de dados faltantes, como identificado anteriormente.

In [ ]:
# Analisando a exitencia de duplicatas